name: NestJS CI and Deployment

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # Use the Node.js version that matches your production environment

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          ENV: ${{ secrets.ENV }}
          PORT: ${{ secrets.PORT }}
        run: npm run build

      - name: Run linter
        run: npm run lint
